### PR TITLE
[CSL-2323] Send problem description also as a comment

### PR DESCRIPTION
**Pull request by StavrosChryselis**

### CODE REVIEW

**Review by jcmincke — APPROVED** [review]

**Review by jcmincke — APPROVED** [review]

**Review by volhovm — CHANGES_REQUESTED** [review]
@StavrosChryselis minor version bump

**Review by volhovm — APPROVED** [review]

**Comment by volhovm** [comment]
Next time please include task id into your branch name. General convention would suggest `stavros/csl2323`. Thx!

**Comment by StavrosChryselis** [comment]
Noted!

**Comment by domenkozar** [comment]
Please also make a bump in cardano-sl and notify us once it's ready to be deployed :)

**Comment by volhovm** [comment]
cc @StavrosChryselis

**Pull request merged**
